func to check if a command is valid before you run it"

diff --git a/aliases b/aliases
--- a/aliases
+++ b/aliases
@@ -1,31 +1,24 @@
 #!/usr/bin/env bash
 
-# postgresql server
-alias pgdown="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
-alias pgup="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
-alias pgstatus='pg_ctl status'
-
-# ipython qtconsole
-alias jupyter='jupyter console --colors linux'
-alias ipython='ipython console --colors linux'
-alias ipy='ipython'
-alias ipyq='ipython qtconsole'
-alias ipynb='ipython notebook'
-
-# vhosts
-alias hosts='sudo vim /etc/hosts'
-alias vhosts='sudo vim /etc/apache2/extra/httpd-vhosts.conf'
-
-# cleanup aliases
-# remove .DS_Store recursively
-alias rmdss="find . -name '*.DS_Store' -type f -delete"
-# remove .swo recursively
-alias rmswo="find . -name '*.swo' -type f -delete"
-# remove .swp recursively
-alias rmswp="find . -name '*.swp' -type f -delete"
-
-# remove pyc files recursively
-alias rmpyc="find . -name '*.pyc' -type f -delete"
+is_valid_command () { 
+    : '
+    Use 1st arg for command substitution. concat 1..n args together 
+        is_valid_command "ls --color -F --quote-name" => splits into `ls` + `--color...`
+    '
+    i=0
+    param_str=""
+    for word in $(echo "$@"); do
+        if [ $i -eq 0 ] ; then
+            cmd_str="$word"
+        else
+            param_str="$param_str $word"
+        fi
+        i=$[i +1]
+    done
+    type $cmd_str &> /dev/null && 
+        eval $(echo "$cmd_str $param_str") &> /dev/null
+        # debug with `echo "$?"`
+}
 
 # copy working directory
 # or pass filename to get the path to that file
@@ -45,33 +38,55 @@ function cwd() {
     echo -e "$P" | tr -d '\r\n' | pbcopy
 }
 
+# DATABASES
+alias pgdown="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
+alias pgup="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
+alias pgstatus='pg_ctl status'
+
+# IPYTHON
+alias jupyter='jupyter console --colors linux'
+alias ipython='ipython console --colors linux'
+alias ipy='ipython'
+alias ipyq='ipython qtconsole'
+alias ipynb='ipython notebook'
+
+# SAFE CLEANUP - delete junk files safely + recursively
+alias rmdss="find . -name '*.DS_Store' -type f -delete"
+alias rmswo="find . -name '*.swo' -type f -delete"
+alias rmswp="find . -name '*.swp' -type f -delete"
+alias rmpyc="find . -name '*.pyc' -type f -delete"
+alias rmjunk="rmdss && rmswo && rmswp && rmpyc && clear"
+
+
 alias excel="open -a Microsoft\ Excel"
 alias chrome="open -a Google\ Chrome"
 
-# copy file interactive
+# interactive copy + move comamnds to prompt before overwriting files
 alias cp='cp -i'
-
-# move file interactive
 alias mv='mv -i'
 
-# untar
+
+# untar / archive data formats
 alias untar='tar xvf'
 
-# make new directory and  cd into it
+# make a folder and cd into it.
 function mkd () { mkdir -p "$@" && cd "$@"; }
 
-# OS X `ls` command
-export LSCOLORS=gxfxcxdxbxegedabagacad # Dark lscolor scheme
-
-# GNU `ls` (installs w/ coreutils on OS X)
-export LS_COLORS='no=00:fi=00:di=01;34:ln=01;36:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arj=01;31:*.taz=01;31:*.lzh=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.gz=01;31:*.bz2=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.avi=01;35:*.fli=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.ogg=01;35:*.mp3=01;35:*.wav=01;35:'
+# dircolors is only relevant if you are using 
+if is_valid_command dircolors; then
+    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
+    alias ls='ls --color=auto'
+    alias grep='grep --color=auto'
+    alias fgrep='fgrep --color=auto'
+    alias egrep='egrep --color=auto'
+fi
 
 # Detect which `ls` flavor is in use
-if ls -F --color --quote-name > /dev/null 2>&1; then 
+if is_valid_command ls -F --color --quote-name; then
     # GNU `ls`
-    # -F              => append indicator (e.g. * for executables and / for directories)
-    # --quote-name    => surround folder names in quotes
-    # -N              => print raw entry names 
+    # -F            => append indicator (e.g. * for executables and / for directories)
+    # --quote-name  => surround folder names in quotes
+    # -N            => print raw entry names 
     colorflag="-FN --color"
 else 
     # OS X `ls`
@@ -81,18 +96,12 @@ else
     colorflag="-GFp"
 fi
 
-alias ls="ls ${colorflag}"
-
-# colorize grep matches
-alias grep="grep --color=auto"
-alias fgrep="fgrep --color=auto"
-alias egrep="egrep --color=auto"
-
 alias ~='cd ~'
 alias ..='cd ..'
 alias ..2='cd ..'
 alias o='open '
 alias h='history '
+alias ls="ls ${colorflag}"
 
 # Long list colorized w/ size in human understandable form
 alias ll='ls -lh'
@@ -103,8 +112,11 @@ alias la="ls -lha"
 # List only directories
 alias lsd='ls -dl */'
 
-# List current directory contents by last modified descending.
+# `ls` by last modified date descending
 alias lst="ls -lt"
+
+# `ls` only hidden files
+alias lh="ls -ld .[!.]*"
 
 function followers() {
     SCREEN_NAME=`t whoami | grep Name | cut -d',' -f1 | cut -d'e' -f2`
